# Generated by Django 4.2.21 on 2025-09-02 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('inn', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ИНН')),
                ('bik', models.CharField(blank=True, max_length=255, null=True, verbose_name='ВИК')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('ogrn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('gen_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Генеральный директор')),
                ('r_s', models.CharField(blank=True, max_length=255, null=True, verbose_name='р/с')),
                ('k_s', models.CharField(blank=True, max_length=255, null=True, verbose_name='к/с')),
                ('has_skud', models.BooleanField(default=False, verbose_name='СКУД')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OrganizationTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('editable', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табели',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orgdocs/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользовател')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('inn', models.CharField(db_index=True, max_length=20, verbose_name='ИНН')),
                ('bik', models.CharField(blank=True, max_length=255, null=True, verbose_name='ВИК')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('ogrn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('gen_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Генеральный директор')),
                ('r_s', models.CharField(blank=True, max_length=255, null=True, verbose_name='р/с')),
                ('k_s', models.CharField(blank=True, max_length=255, null=True, verbose_name='к/с')),
                ('has_skud', models.BooleanField(default=False, verbose_name='СКУД')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Организация',
                'verbose_name_plural': 'historical Организации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='doc/')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerToOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checking', 'Checking'), ('done', 'Done')], max_length=20, null=True, verbose_name='Статус')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('client', 'Client'), ('worker', 'Worker')], default='worker', max_length=20, verbose_name='Роль')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Пользовател')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'unique_together': {('org', 'worker')},
            },
        ),
    ]
