# Generated by Django 4.2.21 on 2025-09-02 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('main', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Тип документов',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=255, unique=True, verbose_name='Паспорт')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWorkerDoc',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, editable=False, verbose_name='Дата создание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начало')),
                ('expired_date', models.DateField(blank=True, null=True, verbose_name='Дата окончание')),
                ('file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Файл')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.doctype', verbose_name='Тип документа')),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workers.worker', verbose_name='Пользовател')),
            ],
            options={
                'verbose_name': 'historical Документа сотрудника',
                'verbose_name_plural': 'historical Документы сотрудника',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkerDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начало')),
                ('expired_date', models.DateField(blank=True, null=True, verbose_name='Дата окончание')),
                ('file', models.FileField(blank=True, null=True, upload_to='user-docs', verbose_name='Файл')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.doctype', verbose_name='Тип документа')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker', verbose_name='Пользовател')),
            ],
            options={
                'verbose_name': 'Документа сотрудника',
                'verbose_name_plural': 'Документы сотрудника',
                'unique_together': {('type', 'worker')},
            },
        ),
    ]
